# Generated by Django 5.2.8 on 2025-11-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_sellerprofiletable_userprofiletable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofiletable',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=20),
        ),
    ]
