# Generated by Django 5.2.8 on 2025-11-26 10:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_sellerprofiletable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiletable',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
