# Generated by Django 5.2.8 on 2025-11-26 10:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofiletable_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofiletable',
            name='store_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store_logo'),
        ),
    ]
